[package]
name = "inventory_manager"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = "21.1.1"

[dev-dependencies]
soroban-sdk = { version = "21.1.1", features = ["testutils"] }
